language: node_js
sudo: false
node_js:
- 0.12
env:
  global:
  - SAUCE_USERNAME=ko-css3-animation
  - secure: DJMxTosN0o9VncvGrmlfUMf0/4KLepU87L0R87/IomE+vrw7ahj/hmoj9YiEtKv9BycmVndGrdYS1jH05YcTbUH+pwXWbTzr9TzAfipQ+ja6HHmnIZ0ndeHxOk/q6azHqO0G/xuvk5u2LIh8JjK2r5p474Nk9sM2A6WBTMDDkk4Ty9ZIlj2Jb23mvRCgY2RkVijem0XfAuK9AeZmrNmrg0/tAhPIvXEHafbL8aDGBhKwUHwjsiO77LPVK9cfdmyD23aKR9EPpUbbwhaNN+wfYvxp26aoN3eR41EurgRqoaZ9iM7boHJ4HO4B2pPdW2WOzBEzoD3J5/2JpmQROx8fcwTh5K9Mbrb/8RypL5xinFV1GoEwY+TljKlUz2Y8e7dlgZn8hKoTi5TWH7iGdGXi7GcQ1b3pOSqgnO3yGm3WWIUOSnUTZeefU2ITayFePlbqj7AdfTEBWyRdF3c2563iHi37/RDoFhG8Io6+QoDec4p0x/Z6kip3gP5FMow5owty8vSoE1qg7YDuAWfxdmtRlVr/XY4ohmAOXXuZcgx7ffrASrhOGzOZFambl3bKgDmSKGfI3+PSh/xbA5M/yoKY3E0zpe5ThcpZTLYI8TawIQPJvQp5pxTlEPknZNhaYZC0vVEnwOIxnQlkcGsanR8swaHsA07U6eHudl9cB0HaZs8=
script: npm test
